server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/ai-edu"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000
  outbound:
    identity:
      google:
        redirect-uri: "http://localhost:5173/google-callback"

eureka:
  client:
    serviceUrl:
      defaultZone:

springdoc:
  cache:
    disabled: true
  version: "@springdoc.version@"
  api-docs:
    version: openapi_3_1

otp:
  expiry:
    minutes: 5

jwt:
  signerKey: "sjx+LICVA9ICqRYhJBe9b76m1Sqz28cejEBXvj6ZNVXFXHRHVjyc0JfnXkdB56tN"
